config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'frauds/index'

  devise_for :users
  resources :frauds
  root 'frauds#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attached.rb
class Attached < ActiveRecord::Base
  belongs_to :description
  belongs_to :comment
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :fraud
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :fraud
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fraud
  belongs_to :user
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :fraud
  # validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  # validates :email, email_format: { message: "doesn't look like an email address" }
end

app/models/fraud.rb
class Fraud < ActiveRecord::Base
  self.inheritance_column = nil
  has_many :cards, :dependent => :destroy
  has_many :phones, :dependent => :destroy
  has_many :emails, :dependent => :destroy
  has_many :skypes, :dependent => :destroy
  has_many :cities, :dependent => :destroy
  has_many :regions, :dependent => :destroy
  validates :type, presence: true
  validates :firstname, length: { maximum: 50 }
  validates :lastname, length: { maximum: 50 }
  validates :patronymic, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }
  validates_associated :phones,length: {maximum: 10 }
  # validates :phones,length: {maximum: 10 }
  # validates :description, length: { maximum: 10 }
  # has_many :descriptions, :dependent => :destroy
  default_scope ->{order('created_at DESC')}
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :fraud
  # validates :phone,length: {maximum: 10 }
end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :fraud
end

app/models/skype.rb
class Skype < ActiveRecord::Base
  belongs_to :fraud
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :fraud
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/frauds_controller.rb
class FraudsController < ApplicationController
  def index
    @search = Fraud.ransack(params[:q])
    if !params[:q].nil?
      @frauds = @search.result
    else
     @frauds=Fraud.all
    end
  end
  def new
    @fraud=Fraud.new
    # if @fraud.valid?
    #   @fraud.save
    # else
    #   render(:action => :new)
    # end
  end
  def create
    @fraud=Fraud.new(fraud_params)

    if @fraud.save
      # if params[:fraud][:cards].any? {|element| element.last!= '' }
      params[:fraud][:cards].each do |card|
        @fraud.cards.create(card: card.last) unless card.last.blank?
      end
      # end



      # unless params[:fraud][:cards].first.last.blank?
      #   params[:fraud][:cards].each do |card|
      #     @fraud.cards.create(card: card.last) # card.last - card.value
      #   end
      # end
      unless params[:fraud][:phones].first.last.blank?
        params[:fraud][:phones].each do |phone|
          # if @fraud.phones.new(phone: phone.last).valid?
          @fraud.phones.create!(phone: phone.last) # card.last - card.value
          # else
          #   render(:action => :new)
          # end
        end
      end
      unless params[:fraud][:emails].first.last.blank?
        params[:fraud][:emails].each do |email|
          @fraud.emails.create(email: email.last) # card.last - card.value
        end
      end
      unless params[:fraud][:skypes].first.last.blank?
        params[:fraud][:skypes].each do |skype|
          @fraud.skypes.create(skype: skype.last) # card.last - card.value
        end
      end
      unless params[:fraud][:cities].first.last.blank?
        params[:fraud][:cities].each do |city|
          @fraud.cities.create(city: city.last) # card.last - card.value
        end
      end
      unless params[:fraud][:regions].first.last.blank?
        params[:fraud][:regions].each do |region|
          @fraud.regions.create(region: region.last) # card.last - card.value
        end
      end
        redirect_to :root
    else
      render(:action => :new)
    end
  end
  private
  def fraud_params
    params.require(:fraud).permit( :name,:firstname,:lastname,:patronymic,:icq,:type,:status,:description,:cards,:user_id )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frauds_helper.rb
module FraudsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/frauds/index.html.haml
.container-fluid
  .row
    .col-xs-1
    .col-xs-4
      %strong
        Frauds list
      %br
      - @frauds.each do |fraud|
        %br
        .panel.panel-default
          .panel-heading
            -unless fraud.firstname.blank?
              Firstname:
              %strong
                = fraud.firstname
            -unless fraud.lastname.blank?
              Lastname:
              %strong
                = fraud.lastname
            -unless fraud.patronymic.blank?
              Patronymic:
              %strong
                = fraud.patronymic
          .panel-body
            -unless fraud.icq.blank?
              icq:
              %strong
                = fraud.icq
              %br
            -unless fraud.type.blank?
              Type:
              %strong
                = fraud.type
              %br
            -unless fraud.name.blank?
              Name:
              %strong
                = fraud.name
              %br
            -unless fraud.description.blank?
              Description:
              %strong
                = fraud.description
            -unless fraud.cards.empty?
              Card:
              %strong
                - fraud.cards.each do|card|
                  %br
                  =card.card
              %br
            -unless fraud.phones.empty?
              Phone:
              %strong
                - fraud.phones.each do|phone|
                  %br
                  =phone.phone
              %br
            -unless fraud.emails.empty?
              Email:
              %strong
                - fraud.emails.each do|email|
                  %br
                  =email.email
              %br
            -unless fraud.skypes.empty?
              Skype:
              %strong
                - fraud.skypes.each do|skype|
                  %br
                  =skype.skype
              %br
            -unless fraud.cities.empty?
              City:
              %strong
                - fraud.cities.each do|city|
                  %br
                  =city.city
              %br
            -unless fraud.regions.empty?
              Region:
              %strong
                - fraud.regions.each do|region|
                  %br
                  =region.region
    .col-xs-3
    .col-xs-4
      %strong
        Search fraud
      %br
      %br
      =search_form_for @search do |f|
        -#= f.label :firstname

        = f.label :select_type
        %br
        =f.select :type_cont, ['','частное лицо', 'фирма','покупатель']
        %br
        =f.search_field :firstname, placeholder: 'firstname'
        %br
        -#= f.label :lastname
        =f.search_field :lastname_cont, placeholder: 'lastname'
        %br
        -#= f.label :patronymic
        =f.search_field :patronymic_cont, placeholder: 'patronymic'
        %br
        -#= f.label :icq
        =f.search_field :icq_cont, placeholder: 'icq'
        %br
        -#= f.label :name
        =f.search_field :name, placeholder: 'name'
        %br
        =f.search_field :cards_card_start, placeholder: 'card'
        %br
        =f.search_field :phones_phone_start, placeholder: 'phone'
        %br
        =f.search_field :emails_email_start, placeholder: 'email'
        %br
        =f.search_field :skypes_skype_start, placeholder: 'skype'
        %br
        =f.search_field :cities_city_start, placeholder: 'city'
        %br
        =f.search_field :regions_region_start, placeholder: 'region'


        =f.submit class:"search"

app/views/frauds/new.html.haml
.row
  .col-md-1
  .col-md-5
    + add fraud
    %br
      %br

    =form_for @fraud do |f|
      = f.label :select_type
      - @fraud.errors.full_messages.each do |msg|
        %li= msg
      %br
      -#=f.radio_button('fraud','type','частноелицо')
      -#=f.radio_button('fraud','type' 'фирма')
      -#=f.radio_button('fraud', 'type','покупатель')
      = f.radio_button :type, 'частное лицо',checked:"checked"
      = f.label :type, 'частное лицо', value:'частное лицо'
      = f.radio_button :type, 'фирма'
      = f.label :type, 'фирма', value:'фирма'
      = f.radio_button :type, 'покупатель'
      = f.label :type, 'покупатель', value:'покупатель'
      %br
      = f.text_field :firstname, placeholder: 'firstname'
      %br
      = f.text_field :lastname, placeholder: 'lastname'
      %br
      = f.text_field :patronymic,placeholder: 'patronymic'
      %br
      = f.text_field :icq,placeholder: 'icq'
      %br
      = f.text_field :name,placeholder: 'name'
      %br
      = f.text_area :description,placeholder: 'description'
      %br
      -#= f.text_field :cards,placeholder: 'card', value: ''
      .field_card
        =f.fields_for :cards do|cards_form|
          = cards_form.text_field :card1,placeholder: 'card'
        .btn.btn-default.add{:onclick => "AddFieldCard()"}+
      .field_phone
        =f.fields_for :phones do|phones_form|
          = phones_form.text_field :phone1, maxlength:"10",minlength:"10", placeholder: 'phone'
        .btn.btn-default.add{:onclick => "AddFieldPhone()"}+
      .field_email
        =f.fields_for :emails do|emails_form|
          = emails_form.text_field :email1,type:"email",placeholder: 'email'
        .btn.btn-default.add{:onclick => "AddFieldEmail()"}+
      .field_skype
        =f.fields_for :skypes do|skypes_form|
          = skypes_form.text_field :skype1,placeholder: 'skype'
        .btn.btn-default.add{:onclick => "AddFieldSkype()"}+
      .field_city
        =f.fields_for :cities do|cities_form|
          = cities_form.text_field :city1,placeholder: 'city'
        .btn.btn-default.add{:onclick => "AddFieldCity()"}+
      .field_region
        =f.fields_for :regions do|regions_form|
          = regions_form.text_field :region1,placeholder: 'region'
        .btn.btn-default.add{:onclick => "AddFieldRegion()"}+
      %br
      -#=f.fields_for :descriptions do|descriptions_form|
      -#  = descriptions_form.text_erea :description1,placeholder: 'description'
      -#  %br
      =f.submit class: "btn btn-submit"

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      Rouge
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top
      .navbar-inner
        .container
          .pull-left
            %br
            = link_to "Rouge", root_path,class:"rouge"
            %br
          .navbar-right
            - if user_signed_in?
              %br
              Hello
              = succeed "" do
                %strong= current_user.email
              -#-if current_user.image.small_thumb.blank? || !current_user.image.small_thumb.file.exists?
              -#  = image_tag("default.png", size: "30x30", alt: "Avatar",class:"img-circle")
              -#-else
              -#  = image_tag(current_user.image.small_thumb,class:"img-circle")
              .pull-right
                = link_to "edit profile", edit_user_registration_path, :class => 'navbar-link',class:"btn btn-default menu"
                =link_to "+add fraud",new_fraud_path, :class => 'navbar-link',class:"btn btn-default menu"
                =link_to "logout", destroy_user_session_path, method: :delete, :class => 'navbar-link',class:"btn btn-default menu"

            - else
              =t :hello_guest
              =link_to "login", new_user_session_path, :class => 'navbar-link',class:"btn btn-default menu"
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield